In [1]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/dim_tempo_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 232
Colunas: 7
  data_referencia   ano  mes  trimestre dia_semana  ano_mes  tempo_id
0      2015-04-18  2015    4          2   Saturday  2015-04       197
1      2017-09-20  2017    9          3  Wednesday  2017-09       144
2      2017-09-21  2017    9          3   Thursday  2017-09       145
3      2017-09-27  2017    9          3  Wednesday  2017-09       146
4      2020-04-14  2020    4          2    Tuesday  2020-04       209
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  232 non-null    datetime64[ns]
 1   ano              232 non-null    int32
 2   mes              232 non-null    int32
 3   trimestre        232 non-null    int32
 4   dia_semana       232 non-null    object
 5   ano_mes          232 non-null    object
 6   tempo_id         232 non-null    int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 10.1+ KB
None

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  232 non-null    datetime64[ns]
 1   ano              232 non-null    int32
 2   mes              232 non-null    int32
 3   trimestre        232 non-null    int32
 4   dia_semana       232 non-null    object
 5   ano_mes          232 non-null    object
 6   tempo_id         232 non-null    int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 10.1+ KB

In [3]:
df.isnull().sum()

data_referencia    0
ano                0
mes                0
trimestre          0
dia_semana         0
ano_mes            0
tempo_id           0
dtype: int64

In [4]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/dim_hospital_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 522
Colunas: 17
  id_hospital codigo_municipio nome_municipio_hospital  latitude_hospital  \
0     0013102           410020            Adrianópolis           -24.6606
1     0013129           410030           Agudos do Sul           -25.9899
2     0013633           410400   Campina Grande do Sul           -25.3044
3     0013838           410420             Campo Largo           -25.4525
4     0013846           410420             Campo Largo           -25.4525

   longitude_hospital  leitos_totais  leitos_contratados  leitos_sus  \
0            -48.9922              3                   0           3
1            -49.3343             12                   0          12
2            -49.0551            483                   0         411
3            -49.5290            156                   0         145
4            -49.5290            884                   0         838

   leitos_nao_sus esfera tipo_unidade nivel_hierarquico natureza_juridica  \
0               0                  15                                1244
1               0                  73                                1244
2              72                  05                                3999
3              11                  05                                2062
4              46                  05                                2054

  porte_hospitalar         alta_complexidade esfera_classificacao  \
0      Micro Porte  Baixa/Media Complexidade        Não Informado
1      Micro Porte  Baixa/Media Complexidade        Não Informado
2     Grande Porte  Baixa/Media Complexidade        Não Informado
3     Grande Porte  Baixa/Media Complexidade        Não Informado
4     Grande Porte  Baixa/Media Complexidade        Não Informado

   percentual_sus
0          100.00
1          100.00
2           85.09
3           92.95
4           94.80
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_hospital              522 non-null    object
 1   codigo_municipio         522 non-null    object
 2   nome_municipio_hospital  522 non-null    object
 3   latitude_hospital        522 non-null    float64
 4   longitude_hospital       522 non-null    float64
 5   leitos_totais            522 non-null    int64
 6   leitos_contratados       522 non-null    int64
 7   leitos_sus               522 non-null    int64
 8   leitos_nao_sus           522 non-null    int64
 9   esfera                   522 non-null    object
 10  tipo_unidade             522 non-null    object
 11  nivel_hierarquico        522 non-null    object
 12  natureza_juridica        522 non-null    object
 13  porte_hospitalar         522 non-null    object
 14  alta_complexidade        522 non-null    object
 15  esfera_classificacao     522 non-null    object
 16  percentual_sus           522 non-null    float64
dtypes: float64(3), int64(4), object(10)
memory usage: 69.5+ KB
None

In [7]:
df.isnull().sum()

id_hospital                0
codigo_municipio           0
nome_municipio_hospital    0
latitude_hospital          0
longitude_hospital         0
leitos_totais              0
leitos_contratados         0
leitos_sus                 0
leitos_nao_sus             0
esfera                     0
tipo_unidade               0
nivel_hierarquico          0
natureza_juridica          0
porte_hospitalar           0
alta_complexidade          0
esfera_classificacao       0
percentual_sus             0
dtype: int64

In [8]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/dim_municipio_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 399
Colunas: 4
  codigo_municipio       nome_municipio  latitude  longitude
0           410010               Abatiá  -23.3049   -50.3133
1           410020         Adrianópolis  -24.6606   -48.9922
2           410030        Agudos do Sul  -25.9899   -49.3343
3           410040  Almirante Tamandaré  -25.3188   -49.3037
4           410045   Altamira do Paraná  -24.7983   -52.7128
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   codigo_municipio  399 non-null    object
 1   nome_municipio    399 non-null    object
 2   latitude          399 non-null    float64
 3   longitude         399 non-null    float64
dtypes: float64(2), object(2)
memory usage: 12.6+ KB
None

In [9]:
df.isnull().sum()

codigo_municipio    0
nome_municipio      0
latitude            0
longitude           0
dtype: int64

In [10]:
import pandas as pd

# Carregar o dataset integrado
df = pd.read_parquet('../data/processed/fato_internacao_PR_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 532,538
Colunas: 21
   internacao_id id_hospital codigo_municipio_paciente  tempo_id  \
0              1     2781700                    410050         1
1              2     2781700                    410050         1
2              3     2781700                    410050         1
3              4     2781700                    410050         1
4              5     2781700                    410050         2

  codigo_diagnostico data_internacao data_saida  valor_procedimento  \
0               K359      2023-11-23 2023-11-24               99.73
1               K359      2023-11-23 2023-11-24               48.00
2               K359      2023-11-23 2023-11-24               13.30
3               K359      2023-11-23 2023-11-24                0.00
4               K359      2023-11-27 2023-11-29               89.23

   dias_internacao  paciente_viajou  ... latitude_paciente  \
0                1            False  ...          -23.8759
1                1            False  ...          -23.8759
2                1            False  ...          -23.8759
3                1            False  ...          -23.8759
4                2            False  ...          -23.8759

   longitude_paciente  nome_municipio_hospital latitude_hospital  \
0            -53.8958                  Altônia          -23.8759
1            -53.8958                  Altônia          -23.8759
2            -53.8958                  Altônia          -23.8759
3            -53.8958                  Altônia          -23.8759
4            -53.8958                  Altônia          -23.8759

   longitude_hospital  distancia_estimada_km  ano_competencia  \
0            -53.8958                    0.0             2024
1            -53.8958                    0.0             2024
2            -53.8958                    0.0             2024
3            -53.8958                    0.0             2024
4            -53.8958                    0.0             2024

   mes_competencia  dia_semana  tipo_dia
0                1    Thursday  Dia Util
1                1    Thursday  Dia Util
2                1    Thursday  Dia Util
3                1    Thursday  Dia Util
4                1      Monday  Dia Util

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532538 entries, 0 to 532537
Data columns (total 21 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   internacao_id              532538 non-null  int64
 1   id_hospital                532538 non-null  object
 2   codigo_municipio_paciente  532538 non-null  object
 3   tempo_id                   532538 non-null  int64
 4   codigo_diagnostico         532538 non-null  object
 5   data_internacao            532538 non-null  datetime64[ns]
 6   data_saida                 532538 non-null  datetime64[ns]
 7   valor_procedimento         532538 non-null  float64
 8   dias_internacao            532538 non-null  int64
 9   paciente_viajou            532538 non-null  bool
 10  nome_municipio_paciente    532538 non-null  object
 11  latitude_paciente          532538 non-null  float64
 12  longitude_paciente         532538 non-null  float64
 13  nome_municipio_hospital    532538 non-null  object
 14  latitude_hospital          532538 non-null  float64
 15  longitude_hospital         532538 non-null  float64
 16  distancia_estimada_km      532538 non-null  float64
 17  ano_competencia            532538 non-null  int64
 18  mes_competencia            532538 non-null  int64
 19  dia_semana                 532538 non-null  object
 20  tipo_dia                   532538 non-null  object
dtypes: bool(1), datetime64[ns](2), float64(6), int64(5), object(7)
memory usage: 81.8+ MB
None

In [11]:
df.isnull().sum()

internacao_id                0
id_hospital                  0
codigo_municipio_paciente    0
tempo_id                     0
codigo_diagnostico           0
data_internacao              0
data_saida                   0
valor_procedimento           0
dias_internacao              0
paciente_viajou              0
nome_municipio_paciente      0
latitude_paciente            0
longitude_paciente           0
nome_municipio_hospital      0
latitude_hospital            0
longitude_hospital           0
distancia_estimada_km        0
ano_competencia              0
mes_competencia              0
dia_semana                   0
tipo_dia                     0
dtype: int64

In [19]:
dis = df['codigo_municipio_paciente'].astype(str).str.startswith('41').sum()
dis

np.int64(527117)

In [21]:
dis = df[df['codigo_municipio_paciente'].astype(str).str.startswith('41')]['codigo_municipio_paciente'].nunique()
dis

399

In [22]:
# Extrai os 2 primeiros dígitos de cada código e mostra todos os únicos existentes
outros_numeros = df['codigo_municipio_paciente'].astype(str).str[:2].unique()
print(outros_numeros)

['41' '35' '14' '31' '50' '42' '52' '51' '29' '13' '16' '21' '43' '15'
 '11' '28' '32' '24' '23' '33' '27' '22' '12' '26' '17']

In [ ]:
resultado = df[df['codigo_municipio_paciente'].astype(str).str.startswith('')][['codigo_municipio_paciente', 'paciente_viajou']]
print(resultado)

       codigo_municipio_paciente  paciente_viajou
2684                      140010             True
2685                      140010             True
2686                      140010             True
2687                      140010             True
2688                      140010             True
...                          ...              ...
467148                    140010             True
467149                    140010             True
467150                    140010             True
467151                    140010             True
467152                    140010             True

[102 rows x 2 columns]

In [ ]:
dis1 = df[df['codigo_municipio_paciente'].astype(str).str.startswith('14')]['codigo_municipio_paciente'].nunique()
dis1

2

In [29]:

dis3 = df[df['codigo_municipio_paciente'].astype(str).str.startswith('31')]['codigo_municipio_paciente'].nunique()
dis3

13

In [30]:

dis4 = df[df['codigo_municipio_paciente'].astype(str).str.startswith('50')]['codigo_municipio_paciente'].nunique()
dis4

23

In [31]:
dis5 = df[df['codigo_municipio_paciente'].astype(str).str.startswith('42')]['codigo_municipio_paciente'].nunique()
dis5

73

In [32]:

dis6 = df[df['codigo_municipio_paciente'].astype(str).str.startswith('52')]['codigo_municipio_paciente'].nunique()
dis6

7

In [33]:

dis7 = df[df['codigo_municipio_paciente'].astype(str).str.startswith('51')]['codigo_municipio_paciente'].nunique()
dis7

18

In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('../data/processed/dim_tempo_SP_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 31
Colunas: 7
  data_referencia   ano  mes  trimestre dia_semana  ano_mes  tempo_id
0      2024-01-01  2024    1          1     Monday  2024-01        28
1      2024-01-02  2024    1          1    Tuesday  2024-01         4
2      2024-01-03  2024    1          1  Wednesday  2024-01        21
3      2024-01-04  2024    1          1   Thursday  2024-01        25
4      2024-01-05  2024    1          1     Friday  2024-01        27
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  31 non-null     datetime64[ns]
 1   ano              31 non-null     int32
 2   mes              31 non-null     int32
 3   trimestre        31 non-null     int32
 4   dia_semana       31 non-null     object
 5   ano_mes          31 non-null     object
 6   tempo_id         31 non-null     int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 1.5+ KB
None

In [5]:
df.head(20)

   data_referencia   ano  mes  trimestre dia_semana  ano_mes  tempo_id
0       2024-01-01  2024    1          1     Monday  2024-01        28
1       2024-01-02  2024    1          1    Tuesday  2024-01         4
2       2024-01-03  2024    1          1  Wednesday  2024-01        21
3       2024-01-04  2024    1          1   Thursday  2024-01        25
4       2024-01-05  2024    1          1     Friday  2024-01        27
5       2024-01-06  2024    1          1   Saturday  2024-01        19
6       2024-01-07  2024    1          1     Sunday  2024-01        29
7       2024-01-08  2024    1          1     Monday  2024-01        14
8       2024-01-09  2024    1          1    Tuesday  2024-01        26
9       2024-01-10  2024    1          1  Wednesday  2024-01        24
10      2024-01-11  2024    1          1   Thursday  2024-01        10
11      2024-01-12  2024    1          1     Friday  2024-01        13
12      2024-01-13  2024    1          1   Saturday  2024-01        22
13      2024-01-14  2024    1          1     Sunday  2024-01        11
14      2024-01-15  2024    1          1     Monday  2024-01         5
15      2024-01-16  2024    1          1    Tuesday  2024-01        17
16      2024-01-17  2024    1          1  Wednesday  2024-01        20
17      2024-01-18  2024    1          1   Thursday  2024-01        15
18      2024-01-19  2024    1          1     Friday  2024-01         8
19      2024-01-20  2024    1          1   Saturday  2024-01         7

In [6]:
df2 = pd.read_parquet('../data/processed/dim_municipio_SP_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

Registros: 31
Colunas: 7
  data_referencia   ano  mes  trimestre dia_semana  ano_mes  tempo_id
0      2024-01-01  2024    1          1     Monday  2024-01        28
1      2024-01-02  2024    1          1    Tuesday  2024-01         4
2      2024-01-03  2024    1          1  Wednesday  2024-01        21
3      2024-01-04  2024    1          1   Thursday  2024-01        25
4      2024-01-05  2024    1          1     Friday  2024-01        27
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  31 non-null     datetime64[ns]
 1   ano              31 non-null     int32
 2   mes              31 non-null     int32
 3   trimestre        31 non-null     int32
 4   dia_semana       31 non-null     object
 5   ano_mes          31 non-null     object
 6   tempo_id         31 non-null     int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 1.5+ KB
None

In [7]:
df2.head()

  codigo_municipio    nome_municipio  uf  latitude  longitude     estado
0           350010        Adamantina  SP  -21.6820   -51.0737  Sao Paulo
1           350020            Adolfo  SP  -21.2325   -49.6451  Sao Paulo
2           350030             Aguaí  SP  -22.0572   -46.9735  Sao Paulo
3           350040    Águas da Prata  SP  -21.9319   -46.7176  Sao Paulo
4           350050  Águas de Lindóia  SP  -22.4733   -46.6314  Sao Paulo

In [9]:
df3 = pd.read_parquet('../data/processed/dim_hospital_SP_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

df3.head()

Registros: 31
Colunas: 7
  data_referencia   ano  mes  trimestre dia_semana  ano_mes  tempo_id
0      2024-01-01  2024    1          1     Monday  2024-01        28
1      2024-01-02  2024    1          1    Tuesday  2024-01         4
2      2024-01-03  2024    1          1  Wednesday  2024-01        21
3      2024-01-04  2024    1          1   Thursday  2024-01        25
4      2024-01-05  2024    1          1     Friday  2024-01        27
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  31 non-null     datetime64[ns]
 1   ano              31 non-null     int32
 2   mes              31 non-null     int32
 3   trimestre        31 non-null     int32
 4   dia_semana       31 non-null     object
 5   ano_mes          31 non-null     object
 6   tempo_id         31 non-null     int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 1.5+ KB
None

,id_hospital,codigo_municipio,nome_municipio_hospital,uf_hospital,estado_hospital,latitude_hospital,longitude_hospital,leitos_totais,leitos_sus,leitos_nao_sus,esfera,tipo_unidade,nivel_hierarquico,natureza_juridica,porte_hospitalar,alta_complexidade,percentual_sus
0,0008028,353440,Osasco,SP,Sao Paulo,-23.5324,-46.7916,225,201,24,,05,,1244,Grande Porte,Baixa/Media Complexidade,89.33
1,0008036,353440,Osasco,SP,Sao Paulo,-23.5324,-46.7916,183,175,8,,07,,1244,Grande Porte,Baixa/Media Complexidade,95.63
2,0008052,353440,Osasco,SP,Sao Paulo,-23.5324,-46.7916,250,250,0,,05,,1023,Grande Porte,Baixa/Media Complexidade,100.00
3,0008087,353440,Osasco,SP,Sao Paulo,-23.5324,-46.7916,22,22,0,,20,,1244,Pequeno Porte,Baixa/Media Complexidade,100.00
4,0008141,353440,Osasco,SP,Sao Paulo,-23.5324,-46.7916,12,12,0,,20,,1244,Micro Porte,Baixa/Media Complexidade,100.00

In [10]:
df4 = pd.read_parquet('../data/processed/fato_internacao_SP_2024_01.parquet')

print(f"Registros: {len(df):,}")
print(f"Colunas: {len(df.columns)}")
print(df.head())
print(df.info())

df4.head()

Registros: 31
Colunas: 7
  data_referencia   ano  mes  trimestre dia_semana  ano_mes  tempo_id
0      2024-01-01  2024    1          1     Monday  2024-01        28
1      2024-01-02  2024    1          1    Tuesday  2024-01         4
2      2024-01-03  2024    1          1  Wednesday  2024-01        21
3      2024-01-04  2024    1          1   Thursday  2024-01        25
4      2024-01-05  2024    1          1     Friday  2024-01        27
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_referencia  31 non-null     datetime64[ns]
 1   ano              31 non-null     int32
 2   mes              31 non-null     int32
 3   trimestre        31 non-null     int32
 4   dia_semana       31 non-null     object
 5   ano_mes          31 non-null     object
 6   tempo_id         31 non-null     int64
dtypes: datetime64[ns](1), int32(3), int64(1), object(2)
memory usage: 1.5+ KB
None

,internacao_id,id_hospital,codigo_municipio_paciente,tempo_id,codigo_diagnostico,data_internacao,data_saida,valor_procedimento,dias_internacao,paciente_viajou,...,latitude_paciente,longitude_paciente,nome_municipio_hospital,latitude_hospital,longitude_hospital,distancia_estimada_km,ano_competencia,mes_competencia,dia_semana,tipo_dia
0,1,2087219,350960,1.0,K590,2024-01-28,2024-01-30,0.00,2,False,...,-23.2078,-46.7889,Campo Limpo Paulista,-23.2078,-46.7889,0.000000,2024,1,Sunday,Fim de Semana
1,2,2087219,350960,1.0,K590,2024-01-28,2024-01-30,4.58,2,False,...,-23.2078,-46.7889,Campo Limpo Paulista,-23.2078,-46.7889,0.000000,2024,1,Sunday,Fim de Semana
2,3,2087219,350960,1.0,K590,2024-01-28,2024-01-30,4.59,2,False,...,-23.2078,-46.7889,Campo Limpo Paulista,-23.2078,-46.7889,0.000000,2024,1,Sunday,Fim de Semana
3,4,2087219,352520,2.0,T022,2024-01-29,2024-01-29,29.21,0,True,...,-23.1039,-46.7280,Campo Limpo Paulista,-23.2078,-46.7889,13.124071,2024,1,Monday,Dia Util
4,5,2087219,352520,2.0,T022,2024-01-29,2024-01-29,0.00,0,True,...,-23.1039,-46.7280,Campo Limpo Paulista,-23.2078,-46.7889,13.124071,2024,1,Monday,Dia Util

In [ ]:
df4[]